# Generated by Django 4.0.1 on 2022-01-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0002_delete_driver_delete_rides_alter_userinfo_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Driver Name')),
                ('vehicle_type', models.CharField(max_length=30, verbose_name='Vehicle Type')),
                ('license_number', models.CharField(max_length=30, verbose_name='License Plate Number')),
                ('capacity', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Passenger Capacity')),
                ('special_vehicle_info', models.TextField(verbose_name='Special Vehicle Information')),
            ],
        ),
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Request_id')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination')),
                ('arrive_date', models.DateTimeField(verbose_name='Request Arrival Date and Time')),
                ('number_passenger', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Passenger Number')),
                ('share', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Share Ride')),
                ('status', models.CharField(choices=[('OP', 'Open'), ('CF', 'Confirmed'), ('CL', 'Closed')], max_length=20, verbose_name='Status')),
                ('vehicle_type', models.CharField(max_length=20, verbose_name='Vehicle Requirement')),
                ('special_request', models.TextField(verbose_name='Special Request')),
            ],
        ),
    ]
