# Generated by Django 4.0.1 on 2022-01-24 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rideshare', '0004_delete_userinfo_driver_username_rides_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='username',
        ),
        migrations.AlterField(
            model_name='rides',
            name='number_passenger',
            field=models.PositiveIntegerField(default=1, verbose_name='Passenger Number'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
