# Generated by Django 4.0.1 on 2022-01-25 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rideshare', '0006_alter_rides_share_alter_rides_special_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='share',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=5, verbose_name='Share Ride'),
        ),
        migrations.CreateModel(
            name='sharer_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination')),
                ('arrive_date_early', models.DateTimeField(verbose_name='Request Early Arrival Date and Time')),
                ('arrive_date_late', models.DateTimeField(verbose_name='Request Late Arrival Date and Time')),
                ('number_passenger', models.PositiveIntegerField(default=1, verbose_name='Passenger Number')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
