# Generated by Django 4.0.1 on 2022-01-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0007_alter_rides_share_sharer_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharer_search',
            old_name='share',
            new_name='sharer',
        ),
    ]
