# Generated by Django 4.0.1 on 2022-01-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0008_rename_share_sharer_search_sharer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharer_search',
            name='join_ride',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
