# Generated by Django 2.2.12 on 2022-01-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0012_auto_20220126_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='special_vehicle_info',
            field=models.TextField(blank=True, verbose_name='Special Vehicle Information'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('EC', 'Basic Economy - Affordable, everyday ride'), ('ECXL', 'Economy XL - Affordable rides for groups up to 5'), ('LX', 'Luxury - High-end and newer cars'), ('GR', 'Green- Eco-friendly'), ('PT', 'Pet - Affordable rides for you and your pet')], max_length=20, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='vehicle_type',
            field=models.CharField(choices=[('EC', 'Basic Economy - Affordable, everyday ride'), ('ECXL', 'Economy XL - Affordable rides for groups up to 5'), ('LX', 'Luxury - High-end and newer cars'), ('GR', 'Green- Eco-friendly'), ('PT', 'Pet - Affordable rides for you and your pet')], max_length=20, verbose_name='Vehicle Type'),
        ),
    ]
