# Generated by Django 4.0.1 on 2022-01-30 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0014_alter_driver_id_alter_sharer_search_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('CF', 'Confirmed'), ('CL', 'Closed'), ('CA', 'Cancel')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sharer_search',
            name='number_passenger',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Passenger Number'),
        ),
    ]
