# Generated by Django 2.2.12 on 2022-01-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0015_auto_20220130_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='special_vehicle_info',
            field=models.TextField(blank=True, null=True, verbose_name='Special Vehicle Information'),
        ),
        migrations.AlterField(
            model_name='rides',
            name='special_request',
            field=models.TextField(blank=True, null=True, verbose_name='Special Request'),
        ),
    ]
