# Generated by Django 4.0.1 on 2022-01-30 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0016_auto_20220130_1938'),
        ('rideshare', '0016_rides_has_sharer_alter_driver_capacity_and_more'),
    ]

    operations = [
    ]
